name: deploy.js CI

on:
  push:
    branches: [main, deploy-test]
  pull_request:
    branches: [main, deploy-test]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i
        working-directory: server
      - name: Build
        run: npm run build
        working-directory: server
