name: deploy.js CI

on:
  push:
    branches: [main, deploy-test]
  pull_request:
    branches: [main, deploy-test]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd server
          npm i
          npm run build
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
